### ISSUE TITLE
Kubernetes Client Errors

### ISSUE THREAD

**Issue by john-delivuk** [logzio/apollo#105]
Curious if it's related to the older version of kubernetes client. Looks like it may be obscuring the real error. Also is there an option for loading the CA cert for environment, or is it ignoring TLS errors? We're using self signed cert via kops. 

Thanks for all the hard work, this has been a really neat evaluation to play with. 

```19:43:03.732 [kubernetes-monitor-0] INFO io.logz.apollo.transformers.deployment.DeploymentImageNameTransformer - Setting image of container sample-apollo-app out of deployment id 1 to logzio/sample-apollo-app:df821c0ce4dbacef9c5c79ccf0d4b1a59d150568
19:43:03.738 [kubernetes-monitor-0] ERROR io.logz.apollo.kubernetes.KubernetesHandler - Got exception while deploying to kubernetes deployment id 1. Leaving in its original state
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://[redacted]/apis/extensions/v1beta1/namespaces/default/deployments/sample-apollo-app. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:266)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:656)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:168)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:357)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:355)
	at io.logz.apollo.kubernetes.KubernetesHandler.startDeployment(KubernetesHandler.java:83)
	at io.logz.apollo.kubernetes.KubernetesMonitor.lambda$monitor$0(KubernetesMonitor.java:107)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.logz.apollo.kubernetes.KubernetesMonitor.monitor(KubernetesMonitor.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by john-delivuk** [comment]
I did. I also ran curls from my local machine with the token to validate it could get the permission. I'm curious if this error was masking the true error.

**Comment by roiravhon** [comment]
No, this exception is more higher level.
You might have change the permissions after the initial set? We have a cache for the kubernetes clients that i think we are not clearing if there is a change. Try to restart the container maybe, it will read the settings from the DB on startup
